### ISSUE TITLE
Question About Image Resize, Camera Matrix

### ISSUE THREAD

**Issue by trevor-taeyeop** [Shreeyak/cleargrasp#6]
Hi, Shreeyak 
I have some simple questions related to the image size and camera matrix. 

> **Q1. Can I ask why you only resize the height of the image (256 -> 144)??**  
> Can I ask why not use the origin output of the network (256, 256) size?

> **Q2. Can I ask how to get the camera matrix value??**
> For evaluation, You use the different camera d415, d435. 
> How to know all the images camera intrinsic matrix(included fx, fy) included(training, validation and testset)? 
> It seems like used for the making the ground truth surface normal. 
> Could you explain how to get image camera intrinsic matrix?

https://github.com/Shreeyak/cleargrasp/blob/f49f389ac2fa5e7c8b5e1c66f56c0ea9c02bad9a/eval_depth_completion/config/config.yaml.sample#L41-L46

**Comment by Shreeyak** [comment]
> why you only resize the height of the image (256 -> 144)
We try to keep the original aspect ratio of the camera, to reduce distortion. The depth reconstruction module uses the camera intrinsic parameters and will perform better without distortion in one of the axes. Additionally, we use a small size to increase the inference speed.

> how to get the camera matrix
When using the realsense camera, the intrinsic matrix of each camera can be captured through it's API. When rendering images synthetically, we create the virtual camera with given specifications.

Here's a brief explanation of the params:
Cx, Cy - Center of the image. If the camera is idea, then this is half of the image dimensions in X and Y-axis respectively.
Fx, Fy - Focal Length of the pixels. If you know the image resolution and camera's Field of View (degrees), then you can calculate this, as shown in the [readme - calculation-of-focal-len-in-pixels](https://github.com/Shreeyak/cleargrasp#calculation-of-focal-len-in-pixels-fx-fy). 

> How to know all the images camera intrinsic matrix? (training, validation and testset)
The synthetic data uses a virtual camera, with field of view 69.40deg in X-Axis, 42.56deg in Y-Axis.
The real images dataset has a `camera_intrinsics.yaml` file that describes the intrinsics of the camera used to capture the data. An example can be found at: `cleargrasp/data/sample_dataset/real-val/d435/camera_intrinsics.yaml`.

> It seems like used for the making the ground truth surface normal.
No, the camera matrix was not used for ground truth surface normals (of real images). The surface normals were estimated on the pointclouds using Open3D, documentation [here](http://www.open3d.org/docs/release/tutorial/Basic/pointcloud.html#vertex-normal-estimation).

**Comment by Shreeyak** [comment]
@trevor-taeyeop Does this answer your question?

**Comment by trevor-taeyeop** [comment]
Yes, Thanks for reply.
I have still some questions 

> why you only resize the height of the image (256 -> 144)


In that reason, Why not try to predict  256, 128 during network inference?? 

> It seems like used for the making the ground truth surface normal.


Making the pointclouds, It is natural using the camera matrix.
Did you use the camera matrix from the api??

**Comment by Shreeyak** [comment]
> Did you use the camera matrix from the api??
Yes, the camera matrix and depth image were used to create the pointcloud. Once we had the pointcloud, we used it to estimate the surface normals.

> In that reason, Why not try to predict 256, 128 during network inference??
It is a common approach to either (1) take a center-crop in a square shape from input image or (2) squash the input image to a square shape when running inference. We didn't face any problems with the default 256x256 shape of inference, so we didn't change it.
So the input would be something like 1920x1080p, we resize to 512x512p when we pass to the network. Output of the network is 256x256, and we resize it to 256x144 to bring it back to original aspect ratio.

**Comment by Shreeyak** [comment]
For reference, here are the camera parameters from our Realsense cameras used to capture the real-world images:

```yaml
# Camera Intrinsic Parameters
camera_name: 'D415'
xres: 848           # Image Width
yres: 480           # Image Height
fx: 616             # Focal length in pixels along width
fy: 615             # Focal length in pixels along height
cx: 427             # Center of image in pixels along width
cy: 245              # Center of image in pixels along height
```

```yaml
# Camera Intrinsic Parameters
camera_name: 'D435'
xres: 1280           # Image Width
yres: 720           # Image Height
fx: 921             # Focal length in pixels along width
fy: 921             # Focal length in pixels along height
cx: 642             # Center of image in pixels along width
cy: 359              # Center of image in pixels along height
```

And here are the parameters of the camera used to capture synthetic images. The intrinsic parameters can be calculated as mention in the ReadMe's FAQ:
```json
"camera": {
        "field_of_view": {
            "y_axis_rads": 0.7428327202796936,
            "x_axis_rads": 1.2112585306167603
        },
        "sensor": {
            "height_mm": 18.0,
            "width_mm": 32.0
        },
        "focal_length": {
            "longest_axis": 23.10693359375,
            "unit": "FOV"
        }
}
```
